// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auction/v1/gov.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ActionType int32

const (
	ActionType_ADD_TOKEN    ActionType = 0
	ActionType_REMOVE_TOKEN ActionType = 1
)

var ActionType_name = map[int32]string{
	0: "ADD_TOKEN",
	1: "REMOVE_TOKEN",
}

var ActionType_value = map[string]int32{
	"ADD_TOKEN":    0,
	"REMOVE_TOKEN": 1,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_53a12dd2a5200224, []int{0}
}

type UpdateAllowListProposal struct {
	Denom      string     `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ActionType ActionType `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=auction.v1.ActionType" json:"action_type,omitempty"`
}

func (m *UpdateAllowListProposal) Reset()         { *m = UpdateAllowListProposal{} }
func (m *UpdateAllowListProposal) String() string { return proto.CompactTextString(m) }
func (*UpdateAllowListProposal) ProtoMessage()    {}
func (*UpdateAllowListProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a12dd2a5200224, []int{0}
}
func (m *UpdateAllowListProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateAllowListProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateAllowListProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateAllowListProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAllowListProposal.Merge(m, src)
}
func (m *UpdateAllowListProposal) XXX_Size() int {
	return m.Size()
}
func (m *UpdateAllowListProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAllowListProposal.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAllowListProposal proto.InternalMessageInfo

func (m *UpdateAllowListProposal) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *UpdateAllowListProposal) GetActionType() ActionType {
	if m != nil {
		return m.ActionType
	}
	return ActionType_ADD_TOKEN
}

func init() {
	proto.RegisterEnum("auction.v1.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*UpdateAllowListProposal)(nil), "auction.v1.UpdateAllowListProposal")
}

func init() { proto.RegisterFile("auction/v1/gov.proto", fileDescriptor_53a12dd2a5200224) }

var fileDescriptor_53a12dd2a5200224 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0x4d, 0x2e,
	0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x4f, 0xcf, 0x2f, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x82, 0x8a, 0xea, 0x95, 0x19, 0x4a, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x85, 0xf5,
	0x41, 0x2c, 0x88, 0x0a, 0xa5, 0x0c, 0x2e, 0xf1, 0xd0, 0x82, 0x94, 0xc4, 0x92, 0x54, 0xc7, 0x9c,
	0x9c, 0xfc, 0x72, 0x9f, 0xcc, 0xe2, 0x92, 0x80, 0xa2, 0xfc, 0x82, 0xfc, 0xe2, 0xc4, 0x1c, 0x21,
	0x11, 0x2e, 0xd6, 0x94, 0xd4, 0xbc, 0xfc, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08,
	0x47, 0xc8, 0x9c, 0x8b, 0x3b, 0x11, 0x6c, 0x66, 0x7c, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x9f, 0x91, 0x98, 0x1e, 0xc2, 0x22, 0x3d, 0x47, 0x30, 0x2b, 0xa4, 0xb2, 0x20, 0x35,
	0x88, 0x2b, 0x11, 0xce, 0xd6, 0xd2, 0xe5, 0xe2, 0x42, 0xc8, 0x08, 0xf1, 0x72, 0x71, 0x3a, 0xba,
	0xb8, 0xc4, 0x87, 0xf8, 0x7b, 0xbb, 0xfa, 0x09, 0x30, 0x08, 0x09, 0x70, 0xf1, 0x04, 0xb9, 0xfa,
	0xfa, 0x87, 0xb9, 0x42, 0x45, 0x18, 0x9d, 0x22, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e,
	0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58,
	0x8e, 0x21, 0xca, 0x3e, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0xbd,
	0x28, 0xb1, 0x2c, 0xb3, 0xa4, 0x52, 0xd7, 0xa9, 0x28, 0x33, 0x25, 0x3d, 0x15, 0x9d, 0x9b, 0x9b,
	0x9f, 0x52, 0x9a, 0x93, 0xaa, 0x5f, 0xa1, 0x0f, 0x0b, 0x1c, 0x90, 0x93, 0x8b, 0x93, 0xd8, 0xc0,
	0x5e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x11, 0x8c, 0x66, 0x34, 0x01, 0x00, 0x00,
}

func (m *UpdateAllowListProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateAllowListProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateAllowListProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActionType != 0 {
		i = encodeVarintGov(dAtA, i, uint64(m.ActionType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGov(dAtA []byte, offset int, v uint64) int {
	offset -= sovGov(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UpdateAllowListProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	if m.ActionType != 0 {
		n += 1 + sovGov(uint64(m.ActionType))
	}
	return n
}

func sovGov(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGov(x uint64) (n int) {
	return sovGov(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UpdateAllowListProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateAllowListProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateAllowListProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionType", wireType)
			}
			m.ActionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionType |= ActionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGov(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGov
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGov
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGov
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGov
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGov        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGov          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGov = fmt.Errorf("proto: unexpected end of group")
)
