// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auction/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAuctionPeriodsById struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryAuctionPeriodsById) Reset()         { *m = QueryAuctionPeriodsById{} }
func (m *QueryAuctionPeriodsById) String() string { return proto.CompactTextString(m) }
func (*QueryAuctionPeriodsById) ProtoMessage()    {}
func (*QueryAuctionPeriodsById) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{2}
}
func (m *QueryAuctionPeriodsById) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuctionPeriodsById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuctionPeriodsById.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuctionPeriodsById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuctionPeriodsById.Merge(m, src)
}
func (m *QueryAuctionPeriodsById) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuctionPeriodsById) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuctionPeriodsById.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuctionPeriodsById proto.InternalMessageInfo

func (m *QueryAuctionPeriodsById) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryAuctionPeriodsByIdResponse struct {
	AuctionPeriods []AuctionPeriod `protobuf:"bytes,1,rep,name=auction_periods,json=auctionPeriods,proto3" json:"auction_periods"`
}

func (m *QueryAuctionPeriodsByIdResponse) Reset()         { *m = QueryAuctionPeriodsByIdResponse{} }
func (m *QueryAuctionPeriodsByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuctionPeriodsByIdResponse) ProtoMessage()    {}
func (*QueryAuctionPeriodsByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{3}
}
func (m *QueryAuctionPeriodsByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuctionPeriodsByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuctionPeriodsByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuctionPeriodsByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuctionPeriodsByIdResponse.Merge(m, src)
}
func (m *QueryAuctionPeriodsByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuctionPeriodsByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuctionPeriodsByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuctionPeriodsByIdResponse proto.InternalMessageInfo

func (m *QueryAuctionPeriodsByIdResponse) GetAuctionPeriods() []AuctionPeriod {
	if m != nil {
		return m.AuctionPeriods
	}
	return nil
}

type QueryAuctionByAuctionIdAndPeriodId struct {
	AuctionId uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	PeriodId  uint64 `protobuf:"varint,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
}

func (m *QueryAuctionByAuctionIdAndPeriodId) Reset()         { *m = QueryAuctionByAuctionIdAndPeriodId{} }
func (m *QueryAuctionByAuctionIdAndPeriodId) String() string { return proto.CompactTextString(m) }
func (*QueryAuctionByAuctionIdAndPeriodId) ProtoMessage()    {}
func (*QueryAuctionByAuctionIdAndPeriodId) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{4}
}
func (m *QueryAuctionByAuctionIdAndPeriodId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuctionByAuctionIdAndPeriodId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuctionByAuctionIdAndPeriodId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodId.Merge(m, src)
}
func (m *QueryAuctionByAuctionIdAndPeriodId) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuctionByAuctionIdAndPeriodId) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodId.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodId proto.InternalMessageInfo

func (m *QueryAuctionByAuctionIdAndPeriodId) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *QueryAuctionByAuctionIdAndPeriodId) GetPeriodId() uint64 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

type QueryAuctionByAuctionIdAndPeriodIdResponse struct {
	Auction *Auction `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
}

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) Reset() {
	*m = QueryAuctionByAuctionIdAndPeriodIdResponse{}
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAuctionByAuctionIdAndPeriodIdResponse) ProtoMessage() {}
func (*QueryAuctionByAuctionIdAndPeriodIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{5}
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodIdResponse.Merge(m, src)
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuctionByAuctionIdAndPeriodIdResponse proto.InternalMessageInfo

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) GetAuction() *Auction {
	if m != nil {
		return m.Auction
	}
	return nil
}

type QueryAllAuctionsByBidderAndPeriodId struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PeriodId uint64 `protobuf:"varint,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
}

func (m *QueryAllAuctionsByBidderAndPeriodId) Reset()         { *m = QueryAllAuctionsByBidderAndPeriodId{} }
func (m *QueryAllAuctionsByBidderAndPeriodId) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionsByBidderAndPeriodId) ProtoMessage()    {}
func (*QueryAllAuctionsByBidderAndPeriodId) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{6}
}
func (m *QueryAllAuctionsByBidderAndPeriodId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionsByBidderAndPeriodId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionsByBidderAndPeriodId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodId.Merge(m, src)
}
func (m *QueryAllAuctionsByBidderAndPeriodId) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionsByBidderAndPeriodId) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodId.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodId proto.InternalMessageInfo

func (m *QueryAllAuctionsByBidderAndPeriodId) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryAllAuctionsByBidderAndPeriodId) GetPeriodId() uint64 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

type QueryAllAuctionsByBidderAndPeriodIdResponse struct {
	Auctions []Auction `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions"`
}

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) Reset() {
	*m = QueryAllAuctionsByBidderAndPeriodIdResponse{}
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAllAuctionsByBidderAndPeriodIdResponse) ProtoMessage() {}
func (*QueryAllAuctionsByBidderAndPeriodIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{7}
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodIdResponse.Merge(m, src)
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionsByBidderAndPeriodIdResponse proto.InternalMessageInfo

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) GetAuctions() []Auction {
	if m != nil {
		return m.Auctions
	}
	return nil
}

type QueryHighestBidByAuctionIdAndPeriodId struct {
	AuctionId uint64 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	PeriodId  uint64 `protobuf:"varint,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) Reset()         { *m = QueryHighestBidByAuctionIdAndPeriodId{} }
func (m *QueryHighestBidByAuctionIdAndPeriodId) String() string { return proto.CompactTextString(m) }
func (*QueryHighestBidByAuctionIdAndPeriodId) ProtoMessage()    {}
func (*QueryHighestBidByAuctionIdAndPeriodId) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{8}
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodId.Merge(m, src)
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) XXX_Size() int {
	return m.Size()
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodId.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodId proto.InternalMessageInfo

func (m *QueryHighestBidByAuctionIdAndPeriodId) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) GetPeriodId() uint64 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

type QueryHighestBidByAuctionIdAndPeriodIdResponse struct {
	Bid *Bid `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) Reset() {
	*m = QueryHighestBidByAuctionIdAndPeriodIdResponse{}
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryHighestBidByAuctionIdAndPeriodIdResponse) ProtoMessage() {}
func (*QueryHighestBidByAuctionIdAndPeriodIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c48d70714d6628, []int{9}
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodIdResponse.Merge(m, src)
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHighestBidByAuctionIdAndPeriodIdResponse proto.InternalMessageInfo

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) GetBid() *Bid {
	if m != nil {
		return m.Bid
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "auction.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "auction.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAuctionPeriodsById)(nil), "auction.v1.QueryAuctionPeriodsById")
	proto.RegisterType((*QueryAuctionPeriodsByIdResponse)(nil), "auction.v1.QueryAuctionPeriodsByIdResponse")
	proto.RegisterType((*QueryAuctionByAuctionIdAndPeriodId)(nil), "auction.v1.QueryAuctionByAuctionIdAndPeriodId")
	proto.RegisterType((*QueryAuctionByAuctionIdAndPeriodIdResponse)(nil), "auction.v1.QueryAuctionByAuctionIdAndPeriodIdResponse")
	proto.RegisterType((*QueryAllAuctionsByBidderAndPeriodId)(nil), "auction.v1.QueryAllAuctionsByBidderAndPeriodId")
	proto.RegisterType((*QueryAllAuctionsByBidderAndPeriodIdResponse)(nil), "auction.v1.QueryAllAuctionsByBidderAndPeriodIdResponse")
	proto.RegisterType((*QueryHighestBidByAuctionIdAndPeriodId)(nil), "auction.v1.QueryHighestBidByAuctionIdAndPeriodId")
	proto.RegisterType((*QueryHighestBidByAuctionIdAndPeriodIdResponse)(nil), "auction.v1.QueryHighestBidByAuctionIdAndPeriodIdResponse")
}

func init() { proto.RegisterFile("auction/v1/query.proto", fileDescriptor_73c48d70714d6628) }

var fileDescriptor_73c48d70714d6628 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x4f, 0x4f, 0xd4, 0x4e,
	0x18, 0xc7, 0xb7, 0x0b, 0xbf, 0x05, 0x1e, 0xf2, 0x63, 0xe3, 0xf0, 0x67, 0x97, 0xca, 0x76, 0xb1,
	0x84, 0x04, 0x25, 0xbb, 0x95, 0x35, 0x6a, 0x3c, 0x19, 0x7a, 0x01, 0x6e, 0xd8, 0x9b, 0x7f, 0x12,
	0x6c, 0x99, 0x49, 0x99, 0xd8, 0xdd, 0x29, 0x6d, 0x97, 0xd8, 0x18, 0x13, 0xe3, 0xd9, 0x83, 0x89,
	0x77, 0x5f, 0x82, 0x89, 0xef, 0x82, 0x23, 0x89, 0x17, 0x4f, 0xc6, 0x80, 0x2f, 0xc4, 0x74, 0x66,
	0x3a, 0x14, 0x16, 0x58, 0x38, 0x78, 0x6b, 0xe7, 0xf9, 0x3e, 0xdf, 0xef, 0x67, 0xfa, 0xec, 0x93,
	0x85, 0x39, 0xb7, 0xbf, 0x9b, 0x50, 0xd6, 0xb3, 0x0e, 0xd6, 0xac, 0xfd, 0x3e, 0x89, 0xd2, 0x76,
	0x18, 0xb1, 0x84, 0x21, 0x90, 0xe7, 0xed, 0x83, 0x35, 0x7d, 0xc6, 0x67, 0x3e, 0xe3, 0xc7, 0x56,
	0xf6, 0x24, 0x14, 0x7a, 0xad, 0xd0, 0x19, 0xba, 0x91, 0xdb, 0x8d, 0x65, 0xa1, 0x5e, 0x28, 0xe4,
	0x2e, 0xa2, 0xb2, 0xe0, 0x33, 0xe6, 0x07, 0xc4, 0x72, 0x43, 0x6a, 0xb9, 0xbd, 0x1e, 0x4b, 0xdc,
	0xac, 0x28, 0xfb, 0xcc, 0x19, 0x40, 0xcf, 0x32, 0x82, 0x6d, 0x6e, 0xe6, 0x90, 0xfd, 0x3e, 0x89,
	0x13, 0x73, 0x03, 0xa6, 0xcf, 0x9c, 0xc6, 0x21, 0xeb, 0xc5, 0x04, 0xdd, 0x87, 0x8a, 0x08, 0xad,
	0x6b, 0x8b, 0xda, 0xca, 0x64, 0x07, 0xb5, 0x4f, 0x81, 0xdb, 0x42, 0x6b, 0x8f, 0x1e, 0xfe, 0x6a,
	0x96, 0x1c, 0xa9, 0x33, 0xef, 0x42, 0x8d, 0x1b, 0xad, 0x0b, 0xdd, 0x36, 0x89, 0x28, 0xc3, 0xb1,
	0x9d, 0x6e, 0x61, 0x34, 0x05, 0x65, 0x8a, 0xb9, 0xd1, 0xa8, 0x53, 0xa6, 0xd8, 0x7c, 0x03, 0xcd,
	0x4b, 0xa4, 0x2a, 0x7f, 0x13, 0xaa, 0x32, 0x70, 0x27, 0x14, 0xe5, 0xba, 0xb6, 0x38, 0xb2, 0x32,
	0xd9, 0x99, 0x2f, 0x82, 0x9c, 0x31, 0x90, 0x3c, 0x53, 0xee, 0x19, 0x57, 0xf3, 0x35, 0x98, 0xc5,
	0x30, 0x3b, 0x7f, 0xd8, 0xc2, 0xeb, 0x3d, 0x2c, 0x44, 0x5b, 0x18, 0x35, 0x20, 0x9f, 0xc8, 0x8e,
	0x42, 0x9d, 0x70, 0x73, 0x25, 0xba, 0x0d, 0x13, 0x02, 0x23, 0xab, 0x96, 0x79, 0x75, 0x3c, 0x94,
	0xbd, 0xe6, 0x4b, 0xb8, 0x37, 0x3c, 0x41, 0xdd, 0xac, 0x05, 0x63, 0xd2, 0x57, 0x7e, 0xda, 0xe9,
	0x0b, 0x6e, 0xe4, 0xe4, 0x1a, 0xf3, 0x15, 0x2c, 0x09, 0xf3, 0x20, 0x90, 0xb5, 0xd8, 0x4e, 0x6d,
	0x8a, 0x31, 0x89, 0x8a, 0xfc, 0x75, 0x18, 0x73, 0x31, 0x8e, 0x48, 0x2c, 0x06, 0x36, 0xe1, 0xe4,
	0xaf, 0x57, 0xa3, 0x63, 0x58, 0xbd, 0x86, 0xbb, 0x62, 0x7f, 0x08, 0xe3, 0x92, 0x2b, 0x1f, 0xc7,
	0x45, 0xf0, 0x72, 0x10, 0x4a, 0x6a, 0xee, 0xc2, 0x32, 0x4f, 0xd9, 0xa4, 0xfe, 0x1e, 0x89, 0x13,
	0x9b, 0xe2, 0x7f, 0x30, 0x05, 0x07, 0x5a, 0xd7, 0x0a, 0x51, 0x97, 0xb9, 0x03, 0x23, 0x9e, 0x4c,
	0x99, 0xec, 0x54, 0x8b, 0xf7, 0xb0, 0x29, 0x76, 0xb2, 0x5a, 0xe7, 0x43, 0x05, 0xfe, 0xe3, 0xa6,
	0xc8, 0x83, 0x8a, 0xf8, 0xd5, 0x23, 0xa3, 0xa8, 0x1c, 0x5c, 0x28, 0xbd, 0x79, 0x69, 0x5d, 0xe4,
	0x9a, 0xb5, 0x8f, 0x3f, 0xfe, 0x7c, 0x29, 0xdf, 0x42, 0xd5, 0x7c, 0x7b, 0xe5, 0x7a, 0xa3, 0x4f,
	0x1a, 0xcc, 0x9f, 0x5f, 0x09, 0x75, 0x03, 0xb4, 0x34, 0xe0, 0x3b, 0xb8, 0x3e, 0xfa, 0xea, 0x35,
	0x44, 0x0a, 0xa4, 0xc1, 0x41, 0x6a, 0x68, 0xf6, 0x14, 0x44, 0xa8, 0xac, 0x77, 0x14, 0xbf, 0x47,
	0x5f, 0x35, 0x68, 0x5c, 0xbd, 0x34, 0xed, 0xcb, 0xd2, 0x2e, 0xd6, 0xeb, 0x8f, 0x6e, 0xa6, 0x57,
	0xa0, 0xb3, 0x1c, 0xb4, 0x8a, 0xfe, 0x57, 0xa0, 0x34, 0x21, 0x5d, 0xf4, 0x5d, 0x03, 0x63, 0xc8,
	0x5a, 0x58, 0x83, 0x89, 0x57, 0x36, 0xe8, 0x8f, 0x6f, 0xd8, 0xa0, 0x18, 0x97, 0x39, 0x63, 0x13,
	0x35, 0x14, 0xa3, 0x1b, 0x04, 0x2d, 0x2f, 0x6d, 0x79, 0xbc, 0xa5, 0x25, 0x3e, 0x2d, 0xfa, 0xa6,
	0xc1, 0xe2, 0xd0, 0x35, 0x58, 0x1b, 0x80, 0x18, 0xd6, 0xa2, 0x3f, 0xb9, 0x71, 0x8b, 0x22, 0x5f,
	0xe0, 0xe4, 0x73, 0x68, 0x46, 0x91, 0xef, 0x89, 0xd6, 0x0c, 0xdd, 0x7e, 0x7e, 0x78, 0x6c, 0x68,
	0x47, 0xc7, 0x86, 0xf6, 0xfb, 0xd8, 0xd0, 0x3e, 0x9f, 0x18, 0xa5, 0xa3, 0x13, 0xa3, 0xf4, 0xf3,
	0xc4, 0x28, 0xbd, 0x78, 0xea, 0xd3, 0x64, 0xaf, 0xef, 0xb5, 0x77, 0x59, 0xd7, 0xda, 0x88, 0xdc,
	0x03, 0x9a, 0xa4, 0x2d, 0x3b, 0xa2, 0xd8, 0x27, 0xe7, 0x5f, 0xbb, 0x0c, 0xf7, 0x03, 0x62, 0xbd,
	0x55, 0x01, 0x49, 0x1a, 0x92, 0xd8, 0xab, 0xf0, 0xff, 0xa5, 0x07, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x18, 0x70, 0x2e, 0xd0, 0x24, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	AuctionPeriodsByAuctionId(ctx context.Context, in *QueryAuctionPeriodsById, opts ...grpc.CallOption) (*QueryAuctionPeriodsByIdResponse, error)
	AuctionByAuctionIdAndPeriodId(ctx context.Context, in *QueryAuctionByAuctionIdAndPeriodId, opts ...grpc.CallOption) (*QueryAuctionByAuctionIdAndPeriodIdResponse, error)
	AllAuctionsByBidderAndPeriodId(ctx context.Context, in *QueryAllAuctionsByBidderAndPeriodId, opts ...grpc.CallOption) (*QueryAllAuctionsByBidderAndPeriodIdResponse, error)
	HighestBidByAuctionIdAndPeriodId(ctx context.Context, in *QueryHighestBidByAuctionIdAndPeriodId, opts ...grpc.CallOption) (*QueryHighestBidByAuctionIdAndPeriodIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/auction.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionPeriodsByAuctionId(ctx context.Context, in *QueryAuctionPeriodsById, opts ...grpc.CallOption) (*QueryAuctionPeriodsByIdResponse, error) {
	out := new(QueryAuctionPeriodsByIdResponse)
	err := c.cc.Invoke(ctx, "/auction.v1.Query/AuctionPeriodsByAuctionId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionByAuctionIdAndPeriodId(ctx context.Context, in *QueryAuctionByAuctionIdAndPeriodId, opts ...grpc.CallOption) (*QueryAuctionByAuctionIdAndPeriodIdResponse, error) {
	out := new(QueryAuctionByAuctionIdAndPeriodIdResponse)
	err := c.cc.Invoke(ctx, "/auction.v1.Query/AuctionByAuctionIdAndPeriodId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllAuctionsByBidderAndPeriodId(ctx context.Context, in *QueryAllAuctionsByBidderAndPeriodId, opts ...grpc.CallOption) (*QueryAllAuctionsByBidderAndPeriodIdResponse, error) {
	out := new(QueryAllAuctionsByBidderAndPeriodIdResponse)
	err := c.cc.Invoke(ctx, "/auction.v1.Query/AllAuctionsByBidderAndPeriodId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HighestBidByAuctionIdAndPeriodId(ctx context.Context, in *QueryHighestBidByAuctionIdAndPeriodId, opts ...grpc.CallOption) (*QueryHighestBidByAuctionIdAndPeriodIdResponse, error) {
	out := new(QueryHighestBidByAuctionIdAndPeriodIdResponse)
	err := c.cc.Invoke(ctx, "/auction.v1.Query/HighestBidByAuctionIdAndPeriodId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	AuctionPeriodsByAuctionId(context.Context, *QueryAuctionPeriodsById) (*QueryAuctionPeriodsByIdResponse, error)
	AuctionByAuctionIdAndPeriodId(context.Context, *QueryAuctionByAuctionIdAndPeriodId) (*QueryAuctionByAuctionIdAndPeriodIdResponse, error)
	AllAuctionsByBidderAndPeriodId(context.Context, *QueryAllAuctionsByBidderAndPeriodId) (*QueryAllAuctionsByBidderAndPeriodIdResponse, error)
	HighestBidByAuctionIdAndPeriodId(context.Context, *QueryHighestBidByAuctionIdAndPeriodId) (*QueryHighestBidByAuctionIdAndPeriodIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AuctionPeriodsByAuctionId(ctx context.Context, req *QueryAuctionPeriodsById) (*QueryAuctionPeriodsByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionPeriodsByAuctionId not implemented")
}
func (*UnimplementedQueryServer) AuctionByAuctionIdAndPeriodId(ctx context.Context, req *QueryAuctionByAuctionIdAndPeriodId) (*QueryAuctionByAuctionIdAndPeriodIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionByAuctionIdAndPeriodId not implemented")
}
func (*UnimplementedQueryServer) AllAuctionsByBidderAndPeriodId(ctx context.Context, req *QueryAllAuctionsByBidderAndPeriodId) (*QueryAllAuctionsByBidderAndPeriodIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllAuctionsByBidderAndPeriodId not implemented")
}
func (*UnimplementedQueryServer) HighestBidByAuctionIdAndPeriodId(ctx context.Context, req *QueryHighestBidByAuctionIdAndPeriodId) (*QueryHighestBidByAuctionIdAndPeriodIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HighestBidByAuctionIdAndPeriodId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionPeriodsByAuctionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuctionPeriodsById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionPeriodsByAuctionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.v1.Query/AuctionPeriodsByAuctionId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionPeriodsByAuctionId(ctx, req.(*QueryAuctionPeriodsById))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionByAuctionIdAndPeriodId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuctionByAuctionIdAndPeriodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionByAuctionIdAndPeriodId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.v1.Query/AuctionByAuctionIdAndPeriodId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionByAuctionIdAndPeriodId(ctx, req.(*QueryAuctionByAuctionIdAndPeriodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllAuctionsByBidderAndPeriodId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAuctionsByBidderAndPeriodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllAuctionsByBidderAndPeriodId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.v1.Query/AllAuctionsByBidderAndPeriodId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllAuctionsByBidderAndPeriodId(ctx, req.(*QueryAllAuctionsByBidderAndPeriodId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HighestBidByAuctionIdAndPeriodId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHighestBidByAuctionIdAndPeriodId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HighestBidByAuctionIdAndPeriodId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.v1.Query/HighestBidByAuctionIdAndPeriodId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HighestBidByAuctionIdAndPeriodId(ctx, req.(*QueryHighestBidByAuctionIdAndPeriodId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auction.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AuctionPeriodsByAuctionId",
			Handler:    _Query_AuctionPeriodsByAuctionId_Handler,
		},
		{
			MethodName: "AuctionByAuctionIdAndPeriodId",
			Handler:    _Query_AuctionByAuctionIdAndPeriodId_Handler,
		},
		{
			MethodName: "AllAuctionsByBidderAndPeriodId",
			Handler:    _Query_AllAuctionsByBidderAndPeriodId_Handler,
		},
		{
			MethodName: "HighestBidByAuctionIdAndPeriodId",
			Handler:    _Query_HighestBidByAuctionIdAndPeriodId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAuctionPeriodsById) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuctionPeriodsById) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuctionPeriodsById) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuctionPeriodsByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuctionPeriodsByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuctionPeriodsByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuctionPeriods) > 0 {
		for iNdEx := len(m.AuctionPeriods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuctionPeriods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuctionByAuctionIdAndPeriodId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuctionByAuctionIdAndPeriodId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuctionByAuctionIdAndPeriodId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PeriodId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PeriodId))
		i--
		dAtA[i] = 0x10
	}
	if m.AuctionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Auction != nil {
		{
			size, err := m.Auction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionsByBidderAndPeriodId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionsByBidderAndPeriodId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionsByBidderAndPeriodId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PeriodId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PeriodId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Auctions) > 0 {
		for iNdEx := len(m.Auctions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Auctions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PeriodId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PeriodId))
		i--
		dAtA[i] = 0x10
	}
	if m.AuctionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Bid != nil {
		{
			size, err := m.Bid.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAuctionPeriodsById) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryAuctionPeriodsByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuctionPeriods) > 0 {
		for _, e := range m.AuctionPeriods {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAuctionByAuctionIdAndPeriodId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovQuery(uint64(m.AuctionId))
	}
	if m.PeriodId != 0 {
		n += 1 + sovQuery(uint64(m.PeriodId))
	}
	return n
}

func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Auction != nil {
		l = m.Auction.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAuctionsByBidderAndPeriodId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.PeriodId != 0 {
		n += 1 + sovQuery(uint64(m.PeriodId))
	}
	return n
}

func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Auctions) > 0 {
		for _, e := range m.Auctions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryHighestBidByAuctionIdAndPeriodId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovQuery(uint64(m.AuctionId))
	}
	if m.PeriodId != 0 {
		n += 1 + sovQuery(uint64(m.PeriodId))
	}
	return n
}

func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Bid != nil {
		l = m.Bid.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuctionPeriodsById) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuctionPeriodsById: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuctionPeriodsById: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuctionPeriodsByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuctionPeriodsByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuctionPeriodsByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionPeriods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionPeriods = append(m.AuctionPeriods, AuctionPeriod{})
			if err := m.AuctionPeriods[len(m.AuctionPeriods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuctionByAuctionIdAndPeriodId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuctionByAuctionIdAndPeriodId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuctionByAuctionIdAndPeriodId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodId", wireType)
			}
			m.PeriodId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuctionByAuctionIdAndPeriodIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuctionByAuctionIdAndPeriodIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuctionByAuctionIdAndPeriodIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Auction == nil {
				m.Auction = &Auction{}
			}
			if err := m.Auction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionsByBidderAndPeriodId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionsByBidderAndPeriodId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionsByBidderAndPeriodId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodId", wireType)
			}
			m.PeriodId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionsByBidderAndPeriodIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionsByBidderAndPeriodIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionsByBidderAndPeriodIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auctions = append(m.Auctions, Auction{})
			if err := m.Auctions[len(m.Auctions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHighestBidByAuctionIdAndPeriodId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHighestBidByAuctionIdAndPeriodId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHighestBidByAuctionIdAndPeriodId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodId", wireType)
			}
			m.PeriodId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHighestBidByAuctionIdAndPeriodIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHighestBidByAuctionIdAndPeriodIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHighestBidByAuctionIdAndPeriodIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Bid == nil {
				m.Bid = &Bid{}
			}
			if err := m.Bid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
